$mapping = @{
    "clean_educational_banner_graphic_for_english_to_marathi_asking_giving" = "og-english-to-marathi-directions.png"
    "clean_educational_banner_graphic_for_english_to_marathi_daily_needs_essentials" = "og-english-to-marathi-daily-needs.png"
    "clean_educational_banner_graphic_for_english_to_marathi_emergency_phrases_help" = "og-english-to-marathi-emergency-phrases.png"
    "clean_educational_banner_graphic_for_english_to_marathi_essential_phrases" = "og-english-to-marathi-phrases.png"
    "clean_educational_banner_graphic_for_english_to_marathi_greetings" = "og-english-to-marathi-greetings.png"
    "clean_educational_banner_graphic_for_english_to_marathi_hobbies_free_time" = "og-english-to-marathi-hobbies-freetime.png"
    "clean_educational_banner_graphic_for_english_to_marathi_introductions_meeting" = "og-english-to-marathi-introductions.png"
    "clean_educational_banner_graphic_for_english_to_marathi_nature_landscapes" = "og-english-to-marathi-nature-landscapes.png"
    "clean_educational_banner_graphic_for_english_to_marathi_question_words._split" = "og-english-to-marathi-asking-questions.png"
    "clean_educational_banner_graphic_for_english_to_marathi_shopping_bargaining" = "og-english-to-marathi-shopping-market.png"
    "clean_educational_banner_graphic_for_english_to_marathi_technology_phone._split" = "og-english-to-marathi-technology-phone.png"
    "clean_educational_banner_graphic_for_hindi_to_marathi_advanced_conversation" = "og-hindi-to-marathi-advanced-conversation.png"
    "clean_educational_banner_graphic_for_hindi_to_marathi_advanced_structures" = "og-hindi-to-marathi-advanced-structures.png"
    "clean_educational_banner_graphic_for_hindi_to_marathi_business_finance_trade" = "og-hindi-to-marathi-business.png"
    "clean_educational_banner_graphic_for_hindi_to_marathi_daily_conversation" = "og-hindi-to-marathi-daily-conversation.png"
    "clean_educational_banner_graphic_for_hindi_to_marathi_emotions_feelings_moods" = "og-hindi-to-marathi-emotions.png"
    "clean_educational_banner_graphic_for_hindi_to_marathi_family_home_relations" = "og-hindi-to-marathi-family-home.png"
    "clean_educational_banner_graphic_for_hindi_to_marathi_greetings_first" = "og-hindi-to-marathi-greetings.png"
    "clean_educational_banner_graphic_for_hindi_to_marathi_health_body_symptoms" = "og-hindi-to-marathi-health-body.png"
    "clean_educational_banner_graphic_for_hindi_to_marathi_hobbies_leisure_sports" = "og-hindi-to-marathi-hobbies.png"
    "clean_educational_banner_graphic_for_hindi_to_marathi_literature_terms_poetry" = "og-hindi-to-marathi-literature-words.png"
    "clean_educational_banner_graphic_for_hindi_to_marathi_media_news_politics" = "og-hindi-to-marathi-media-news.png"
    "clean_educational_banner_graphic_for_hindi_to_marathi_postpositions_cases" = "og-hindi-to-marathi-postpositions.png"
    "clean_educational_banner_graphic_for_hindi_to_marathi_pronouns_people_words_i" = "og-hindi-to-marathi-pronouns-people.png"
    "clean_educational_banner_graphic_for_hindi_to_marathi_pronunciation_sounds" = "og-hindi-to-marathi-pronunciation-sounds.png"
    "clean_educational_banner_graphic_for_hindi_to_marathi_question_words._split" = "og-hindi-to-marathi-questions.png"
    "clean_educational_banner_graphic_for_hindi_to_marathi_review_essentials_grammar" = "og-hindi-to-marathi-review-essentials.png"
    "clean_educational_banner_graphic_for_marathi_compound_verbs_root_auxiliary" = "og-grammar-compound-verbs.png"
    "clean_educational_banner_graphic_for_marathi_counting_quantifiers_numbers" = "og-grammar-counting-quantifiers.png"
    "clean_educational_banner_graphic_for_marathi_demonstratives_this_that_here" = "og-grammar-demonstratives.png"
    "clean_educational_banner_graphic_for_marathi_frequency_adverbs_always_never" = "og-grammar-frequency-adverbs.png"
    "clean_educational_banner_graphic_for_marathi_negative_sentences_don_t._bold" = "og-grammar-negation.png"
    "clean_educational_banner_graphic_for_marathi_passive_causative._deep_red_and" = "og-grammar-passive-causative.png"
    "clean_educational_banner_graphic_for_marathi_possessive_pronouns._warm_sunset" = "og-grammar-possessives.png"
    "clean_educational_banner_graphic_for_marathi_postpositions_cases_meanings" = "og-grammar-postpositions.png"
    "clean_educational_banner_graphic_for_marathi_pronouns_i_you_we_they._warm" = "og-grammar-pronouns.png"
    "clean_festive_educational_banner_graphic_for_hindi_to_marathi_festivals_diwali" = "og-hindi-to-marathi-festivals.png"
    "clean_high_resolution_cultural_educational_banner_graphic_for_marathi_festival" = "og-vocabulary-culture-festivals.png"
    "clean_high_resolution_educational_banner_graphic_for_100_marathi_words_for" = "og-vocabulary-beginners.png"
    "clean_high_resolution_educational_banner_graphic_for_english_to_marathi" = "og-english-to-marathi-words.png"
    "clean_high_resolution_educational_banner_graphic_for_english_to_marathi_time" = "og-english-to-marathi-time-seasons.png"
    "clean_high_resolution_educational_banner_graphic_for_english_to_marathi_words" = "og-english-to-marathi-words.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_ability_obligation" = "og-grammar-ability-obligation.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_body_parts_43" = "og-vocabulary-body-parts.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_city_places" = "og-vocabulary-city-places.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_clothing_words" = "og-vocabulary-clothing.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_commands_polite" = "og-grammar-commands-polite.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_conjunctions_and" = "og-vocabulary-connectors.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_daily_expressions" = "og-vocabulary-feelings-adverbs-phrases.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_daily_life_words" = "og-vocabulary-daily-life.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_daily_phrases" = "og-phrases-daily.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_direction_words" = "og-vocabulary-directions-locations.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_emotion_words_say" = "og-vocabulary-emotions.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_family_words" = "og-vocabulary-family.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_food_words" = "og-vocabulary-food.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_fruits_vegetables" = "og-vocabulary-fruits-vegetables.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_health_symptoms" = "og-vocabulary-health-symptoms.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_household_items" = "og-vocabulary-household-items.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_kitchen_items" = "og-vocabulary-kitchen-items.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_money_shopping" = "og-vocabulary-money-shopping.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_nature_words_trees" = "og-vocabulary-nature.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_numbers_time._rich" = "og-vocabulary-numbers-time.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_occupations" = "og-vocabulary-people-occupations.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_personality" = "og-vocabulary-personality-words.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_school_education" = "og-vocabulary-education.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_shapes_geometry" = "og-vocabulary-shapes.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_shopping_words" = "og-vocabulary-shopping.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_technology_words" = "og-vocabulary-technology.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_time_expressions" = "og-vocabulary-time-expressions.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_travel_words" = "og-vocabulary-travel.png"
    "clean_high_resolution_educational_banner_graphic_for_marathi_weather_words_rain" = "og-vocabulary-weather.png"
    "clean_high_resolution_educational_banner_graphic_for_search_marathi_lessons" = "og-search.png"
    "clean_high_resolution_educational_banner_graphic_for_spaced_repetition_review" = "og-review.png"
    "clean_high_resolution_educational_blog_banner_graphic_for_how_to_say_help_in" = "og-blog-how-to-say-help-in-marathi.png"
    "clean_high_resolution_educational_blog_banner_graphic_for_how_to_say_i_like_in" = "og-blog-i-like-in-marathi.png"
    "clean_high_resolution_educational_blog_banner_graphic_for_how_to_say_water_in" = "og-blog-how-to-say-water-in-marathi.png"
    "clean_high_resolution_educational_blog_banner_graphic_for_how_to_shop_in" = "og-blog-how-to-shop-in-marathi.png"
    "clean_high_resolution_educational_blog_banner_graphic_for_how_to_tell_time_in" = "og-blog-how-to-tell-time-in-marathi.png"
    "clean_high_resolution_educational_blog_banner_graphic_for_i_don_t_understand_in" = "og-blog-i-dont-understand-in-marathi.png"
    "clean_high_resolution_educational_blog_banner_graphic_for_thamba_meaning_in" = "og-blog-thamba-meaning-in-marathi.png"
    "clean_high_resolution_educational_blog_banner_graphic_for_this_in_marathi" = "og-blog-this-in-marathi.png"
    "clean_high_resolution_educational_blog_banner_graphic_for_train_station_marathi" = "og-blog-train-station-marathi.png"
    "clean_high_resolution_educational_blog_banner_graphic_for_yes_no_in_marathi" = "og-blog-yes-no-in-marathi.png"
    "clean_high_resolution_educational_blog_index_banner_graphic_for_real_life" = "og-blog.png"
    "clean_high_resolution_educational_phrase_banner_graphic_for_marathi_emergency" = "og-phrases-emergency-phrases.png"
    "clean_high_resolution_educational_phrase_banner_graphic_for_marathi_family_talk" = "og-phrases-family-talk.png"
    "clean_high_resolution_educational_phrase_banner_graphic_for_marathi_greetings" = "og-phrases-greetings.png"
    "clean_high_resolution_educational_phrase_banner_graphic_for_marathi_phrases_1" = "og-phrases-making-plans.png"
    "clean_high_resolution_educational_phrase_banner_graphic_for_marathi_phrases_2" = "og-phrases-phone-and-messaging.png"
    "clean_high_resolution_educational_phrase_banner_graphic_for_marathi_phrases_3" = "og-phrases-business-meetings.png"
    "clean_high_resolution_educational_phrase_banner_graphic_for_marathi_phrases_4" = "og-phrases-presentations-interviews.png"
    "clean_high_resolution_educational_phrase_banner_graphic_for_marathi_phrases_5" = "og-phrases-office-work.png"
    "clean_high_resolution_educational_phrase_banner_graphic_for_marathi_phrases_6" = "og-phrases-shopping.png"
    "clean_high_resolution_educational_phrase_banner_graphic_for_marathi_phrases_7" = "og-phrases-thanking-apologizing.png"
    "clean_high_resolution_educational_phrase_banner_graphic_for_marathi_phrases_8" = "og-phrases-travel.png"
    "clean_high_resolution_educational_phrase_banner_graphic_for_marathi_phrases_9" = "og-phrases-shopping.png"
    "clean_high_resolution_educational_vocabulary_banner_graphic_for_marathi_1" = "og-vocabulary-animals.png"
    "clean_high_resolution_educational_vocabulary_banner_graphic_for_marathi_2" = "og-vocabulary-body-parts.png"
    "clean_high_resolution_educational_vocabulary_banner_graphic_for_marathi_3" = "og-vocabulary-food.png"
    "clean_high_resolution_educational_vocabulary_banner_graphic_for_marathi_adverbs" = "og-vocabulary-adverbs.png"
    "clean_high_resolution_educational_vocabulary_banner_graphic_for_marathi_animal" = "og-vocabulary-animals.png"
    "clean_high_resolution_educational_vocabulary_banner_graphic_for_marathi_bird" = "og-vocabulary-birds.png"
    "clean_high_resolution_educational_vocabulary_banner_graphic_for_marathi_colors" = "og-vocabulary-colors.png"
    "clean_high_resolution_educational_vocabulary_banner_graphic_for_marathi_verbs" = "og-vocabulary-verbs.png"
    "clean_high_resolution_polite_educational_blog_banner_graphic_for_how_to_say" = "og-blog-how-to-say-please-in-marathi.png"
    "clean_high_resolution_romantic_educational_blog_banner_graphic_for_how_to_say_i" = "og-blog-how-to-say-i-love-you-in-marathi.png"
}

$srcRoot = "C:\Users\kumar\Downloads\stitch_marathi_grammar_banner_generator\stitch_marathi_grammar_banner_generator"
$destRoot = "C:\Users\kumar\blog\learn-marathi\public\og"

$copied = 0
$missing = @()

foreach ($dirName in $mapping.Keys) {
    $srcFile = Join-Path $srcRoot $dirName "screen.png"
    $destFile = Join-Path $destRoot $mapping[$dirName]
    
    if (Test-Path $srcFile) {
        Copy-Item $srcFile $destFile -Force
        $copied++
    } else {
        $missing += $dirName
    }
}

Write-Host "Copied: $copied"
if ($missing.Count -gt 0) {
    Write-Host "Missing: $($missing.Count)"
    $missing | ForEach-Object { Write-Host "  $_" }
}