// Shared SFX player for the owner's synthesized sound pack
// (public/games/audio/<category>/<id>.mp3). All files are original,
// generated by tools/make_sfx.py — no external licensing.
//
// Playback rules (per the pack README): one Audio object per id, rewind to 0
// before replaying so rapid taps don't lag; mute setting persisted in
// localStorage; play() no-ops when muted, unsupported, or the file fails.

export type Sfx = {
	play(id: string): void;
	setMuted(muted: boolean): void;
	isMuted(): boolean;
};

export const SFX_MUTED_KEY = 'bol-game-muted';

/** Read the persisted mute flag (shared with the GameShell toggle). */
export function sfxMuted(): boolean {
	try {
		return typeof localStorage !== 'undefined' && localStorage.getItem(SFX_MUTED_KEY) === 'on';
	} catch {
		return false;
	}
}

export function makeSfx(
	manifest: Record<string, string>,
	opts: { storage?: { get(key: string): string | null; set(key: string, value: string): void } } = {}
): Sfx {
	const cache = new Map<string, HTMLAudioElement>();
	let muted = opts.storage
		? opts.storage.get(SFX_MUTED_KEY) === 'on'
		: sfxMuted();

	function audio(id: string): HTMLAudioElement | null {
		const src = manifest[id];
		if (!src || typeof Audio === 'undefined') return null;
		let el = cache.get(id);
		if (!el) {
			el = new Audio(src);
			el.preload = 'auto';
			el.addEventListener('error', () => {
				cache.delete(id);
			});
			cache.set(id, el);
		}
		return el;
	}

	return {
		play(id) {
			if (muted) return;
			const el = audio(id);
			if (!el) return;
			try {
				el.currentTime = 0;
				void el.play().catch(() => {
					/* autoplay guards etc. — silent */
				});
			} catch {
				/* ignore */
			}
		},
		setMuted(m) {
			muted = m;
			try {
				opts.storage?.set(SFX_MUTED_KEY, m ? 'on' : 'off');
			} catch {
				/* ignore */
			}
		},
		isMuted: () => muted,
	};
}
